---
- name: Nginx config
  template:
    src: 'serenity_testnets.conf.j2'
    dest: '/etc/nginx/sites-available/serenity_testnets.conf'
  notify: reload nginx

- name: Symlink the nginx config
  file:
    src: '/etc/nginx/sites-available/serenity_testnets.conf'
    dest: '/etc/nginx/sites-enabled/serenity_testnets.conf'
    state: link
    force: true
  notify: reload nginx

- name: Create the testnet files directory
  file:
    path: '{{eth2_testnet_site_root}}'
    state: directory
    owner: www-data
    group: www-data

- name: Clone the testnet data
  git:
    repo: 'https://github.com/status-im/nim-eth2-testnet-data'
    version: 'master'
    depth: 1
    update: true
    dest: '/opt/nim-eth-testnet-data'
  register: repo

- name: Copy the public tesnet files
  shell: 'cp -r /opt/nim-eth-testnet-data/www/* {{eth2_testnet_site_root}}'
  when: repo.changed

- name: Fix the permissions just in case
  file:
    dest: '{{eth2_testnet_site_root}}'
    owner: 'www-data'
    group: 'www-data'
    recurse: true

